# Mondrian CoffeeScript source files
# See explanation in /README.md

src: !!omap
  - extensions:
    - prototype-extensions
    - set
  - setup:
    - _dir: null
    - settings
    - constants
    - setup
    - utils
    - plugins
    - tracking
  - mixins:
    - mixins
    - events
  - io:
    - io
    - svg
    - png
  - uiClasses:
    - font
    - color
  - lab:
    - lab
    - analysis
    - conversions
  - geometry:
    - transformations
    - posn
    - point
    - polynomial
    - range
    - bounds
    - bezier-antlers
    - path-points
    - points-list
    - points-segment
    - line-segment
    - ray
    - cubic-bezier-line-segment
    - monsvg
    - hover-target
    - line
    - rectangle
    - circle
    - ellipse
    - polygon
    - polyline
    - path
    - text
    - text-editable
    - tspan
    - pathfinder
  - files:
    - file
    - local-file
    - permalink-file
    - dropbox-file
    - demo-files
  - archive:
    - archive
    - event
    - map-event
    - attr-event
    - zindex-event
    - existence-event
    - point-existence-event
  - dom:
    - dom
  - ui:
    - ui
    - logo
    - state
    - selection
    - selection-macros
    - window # TODO move this to browser
    - clipboard
    - error-reporting
    - afk
    - topui
    - tooltips
    - swatch
    - swatch-duo
    - snapping
    - canvas
    - cursor-tracking
    - drag-select
    - transformer
    - hotkeys
    - gallery
    - browser
  - controls:
    - control
    - dropdown
    - number-box
    - text-box
    - slider
  - menu:
    - menu
    - item
    - file-menu
    - edit-menu
    - view-menu
    - about-menu
    - login-menu
    - register-menu
    - geometry-menu
    - account-menu
    - share-menu
    - embed-menu
    - filename-item
    - save-item
    - new-item
    - logout-item
    - open-item
    - dropbox-item
    - download-item
    - z-index-items
  - utilities:
    - utility
    - color-picker
    - current-swatches
    - transform
    - stroke-width
    - typography
    - archive
  - tools:
    - tool
    - cursor
    - paw
    - pen
    - crayon
    - line
    - arbitrary-shape
    - ellipse
    - rectangle
    - type
    - rotate
    - zoom
    - eyedropper
  - services:
    - services
    - local
    - permalink
    - dropbox
  - annotations:
    - annotations
    - grid
  - user:
    - account
  - browser:
    - url
    - browser-file

